let annoyingMessages = [
    "Plz buy my merch",
    "Plz subscribe",
    "I love pokimane UwU",
    "Aggressive UWU intensifies",
    "Your goddamn car warranty is on it's way out. CMERE AND GET IT EXTENDED",
    "Did you know that not subscribing causes global warming? Save the planet, hit that subscribe button!",
    "Subscribe to my channel or your Wi-Fi will be permanently slower",
    "If you don't like and share this post, you'll have bad luck for 7 years",
    "I just had a sandwich, you should know about it. Like this post to learn more about my sandwiches!",
    "Your ex still loves you. Click here to find out who!",
    "Like this post or your crush will never text you",
    "Stop scrolling! If you don't comment 'pizza' in the next 5 seconds, your favorite food will disappear forever",
    "Plz follow for daily pictures of my cat doing absolutely nothing interesting",
    "This is the 37th message. Ignore for bad luck. Share for good luck. Do nothing for mediocre luck",
    "Like this post if you're breathing right now",
    "I found a cure for boredom. It's called subscribing to my channel",
    "I bet you can't comment 'pickle' without looking at your keyboard",
    "Subscribe now and receive absolutely nothing in return",
    "Your phone has a virus. Click here to fix it (and by fix, I mean subscribe)",
    "Don't ignore this message! Ignoring may result in happiness and peace of mind",
    "New Year's resolution: Stop reading annoying messages. Failed in 3...2...1...",
    "Breaking News: My cat just sneezed. Like for more breaking news updates",
    "Type 'I'm a potato' in the comments to win absolutely nothing",
    "The more you ignore me, the stronger I get",
    "This message is so annoying that even I can't stand it. Like for self-awareness",
    "I bet you $1,000,000 you won't share this post. You're not that rich, are you?",
    "I'm not saying aliens are real, but if you don't subscribe, they might abduct you",
    "Congratulations! You just won the award for 'Most Ignored Message'. Share to claim your nonexistent trophy",
    "This message is like a mosquito in your room. Annoying, persistent, and hard to get rid of",
    "Like this post if you have ever eaten pizza. Ignore if you're an alien",
    "This message is so annoying, even Siri refuses to read it out loud",
    "Don't just scroll past! Scroll past and regret it for the rest of your life",
    "This message will self-destruct in 5...4...3...2...nah, just kidding. But seriously, subscribe",
    "99% of people won't share this post. Be part of the 1% who annoy their friends",
    "Your crush is thinking about you right now. JK, click here to subscribe and improve your love life",
    "Like if you're still reading. Comment 'potato' if you're really committed",
    "Subscribe now or the next time you eat pizza, it will be pineapple pizza",
    "You're not cool unless you share this post. Just kidding, you're cool either way. But share it anyway",
    "Roses are red, violets are blue, like this post, or I'll annoy you",
    "This message is like a virus. Once you read it, it spreads to your brain and stays forever",
    "If you ignore this message, your pet goldfish will develop existential thoughts",
    "Click here to unlock the secret to eternal happiness. Spoiler: It involves liking and subscribing",
    "Your horoscope says you should like and share this post for good luck. Trust me, I'm an annoyingologist",
    "This message is more persistent than that one aunt who always asks about your love life",
    "You've scrolled this far, might as well like and subscribe. Do it for the memes",
    "Type 'I'm a ninja' in the comments if you read this far. Don't ask why. Just do it",
    "This post is like a bad joke. The more you hear it, the less funny it gets. But you should still share it",
    "Like this post if you've ever blinked. Ignore if you're a robot",
    "This message is so annoying, it has its own fan club. Join now for exclusive annoying content",
    "Subscribe or the next time you order pizza, they'll forget the cheese",
    "I bet you can't resist the urge to like and share this post. Prove me wrong",
    "Your future self is telling you to hit that subscribe button. Don't let your future self down",
    "This message is like glitter. Once you've read it, it's impossible to get rid of",
    "Like this post if you're still reading. Comment 'banana' if you're truly dedicated",
    "This message is sponsored by the Annoying Messages Association. Join now for even more annoyance",
    "Subscribe and become a member of the exclusive Annoying Messages Fan Club. Benefits include regret and frustration",
    "You're not truly living until you've shared this post. Just kidding, you're alive either way. Share it anyway",
    "This message is like a bad song. Once it's stuck in your head, it never leaves",
    "If you don't like and subscribe, your phone battery will die in the next 2 minutes",
    "Click here to enter the Annoying Messages Olympics. Warning: Only for the mentally tough",
    "You're one click away from eternal glory. Or at least, a momentary feeling of accomplishment. Subscribe now",
    "This message is like a boomerang. It always comes back. Like for infinite annoyance",
    "I bet you thought this message would end. Well, it won't. Share for everlasting annoyance",
    "Like this post if you've ever seen a cat. Ignore if you're from another planet",
    "This post is like a horror movie. The more you watch, the more scared you get. Share if you dare",
    "Subscribe now or your favorite dessert will vanish from existence. Don't risk it",
    "This message is like a time traveler. It's annoying in the past, present, and future",
    "Your keyboard is feeling lonely. Type 'qwerty' in the comments to keep it company",
    "This post is like a bad habit. You know it's annoying, but you can't resist",
    "Like this post if you've ever worn socks. Ignore if you're a sockless rebel"
];

setInterval(function () {
    alert(annoyingMessages[Math.floor(Math.random() * annoyingMessages.length)]);
}, Math.random() * 60000);


